# Read the Docs configuration file for MkDocs projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: Linux
  tools:
      - python >=3
      - setuptools
    run:
      python: "3.8"
      numpy: "1.23"
      pandas: "1.4.3"
      pyranges: "0.0.117"

mkdocs:
  configuration: mkdocs.yml
