  package:
    name: dlr_icf
    version: 1.0.9
  
  source:
    url: https://files.pythonhosted.org/packages/11/aa/5788fe126fe1a86c40c0c02121e7a7c6ec31169277580c77c29346550ea5/dlr_icf-1.0.9.tar.gz
    md5: e7b1c4bb8bf5aebbde3ebebe1eeb94e1 

  build:
    number: 0
  
  requirements:
    build:
      - python >=3
      - setuptools
    run:
      - python >=3
      - numpy >=1.23
      - pandas ==1.4.3
      - pyranges ==0.0.117


  about:
    home: https://github.com/BenxiaHu/DLR_ICF
    license: MIT
    summary: how to run DLR_ICF to analyze DLR and ICF.
    description: DLR_ICF can be used to analyze DLR and ICF.
    dev_url: https://github.com/BenxiaHu/DLR_ICF
